spring:
  application.name: e-commerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/chandecake